### ISSUE TITLE
Moving Joystick Throws Error

### ISSUE THREAD

**Issue by BrandonGuocamole** [metrobot-research/metrobot_dashboard#19]
![image](https://user-images.githubusercontent.com/31668130/96542719-8a7f8600-1257-11eb-9cad-727bab9a83a8.png)

Steps to Reproduce:
1. Checkout development branch
2. Run npm install and npm start
3. Move joystick in any direction

**Comment by caelinsutch** [comment]
This happens when ROS isn't running, a fix would be developing better error handling in this application especially with ROS stuff. Will tackle today maybe

**Comment by caelinsutch** [comment]
Fixed by most recent commit
